assets/urls.py

from django.urls import path
from . import views


app_name = 'assets'
urlpatterns = [
    path('', views.index, name='index'),
    path('hardware/', views.hardware_assets, name='hardware'),
    path('hardware/del/', views.delete_hardware_assets, name='hardware_delete'),
    path('hardware/add/', views.add_hardware_assets, name='hardware_add'),
    path('software/', views.software_assets, name='software'),
    path('software/del/', views.delete_software_assets, name='software_delete'),
    path('software/add/', views.add_software_assets, name='software_add'),
    path('detail/<int:asset_id>/', views.detail, name='detail'),
    path('audit/operation/', views.operation, name='operation'),
    path('audit/login/', views.audit_login, name='audit_login'),
]


login/urls.py
from django.urls import path
from . import views


app_name = 'login'
urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('changepasswd/', views.change_passwd, name='changepasswd'),
    path('userinfo/', views.user_info, name='userinfo'),
]


mycmdb/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('login.urls')),
    path('', include('assets.urls')),
    # path('users/', include('django.contrib.auth.urls')),
]

assets/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
# from users.models import User    # 使用自定义用户模型
from login.models import User    # 使用自定义用户模型

class Asset(models.Model):
    """所有资产的共有数据表"""

    """
    导入django.contrib.auto.models内置的User表，作为我们CMDB项目的用户表，用于保存管理员和批准人员的信息；
    sn这个数据字段是所有资产都必须有，并且唯一不可重复的！通常来自自动收集的数据中；
    name和sn一样，也是唯一的；
    asset_type_choice和asset_status分别设计为两个选择类型
    adamin和approved_by是分别是当前资产的管理员和将该资产上线的审批员，为了区分他们，设置了related_name；
    Asset表中的很多字段内容都无法自动获取，需要我们手动输入，比如合同、备注。
    最关键的是其中的一些外键字段，设置为on_delete=models.SET_NULL，这样的话，当关联的对象被删除的时候，不会影响到资产数据表。
    """

    asset_type_choice = (
        ('server', '服务器'),
        ('networkdevice', '网络设备'),
        ('storagedevice', '存储设备'),
        ('securitydevice', '安全设备'),
        # ('software', '软件资产'), # 软件资产单独一个表
    )

    asset_status = (
        (0, '在线'),
        (1, '下线'),
        (2, '未知'),
        (3, '故障'),
        (4, '备用'),
        )

    asset_type = models.CharField(choices=asset_type_choice, max_length=64, default='server', verbose_name="资产类型")
    name = models.CharField(max_length=64, unique=True, verbose_name="资产名称")     # 不可重复
    sn = models.CharField(max_length=128, unique=True, verbose_name="资产序列号")  # 不可重复
    business_unit = models.ForeignKey('BusinessUnit', null=True, blank=True, verbose_name='所属业务线',
                                      on_delete=models.SET_NULL)
    status = models.SmallIntegerField(choices=asset_status, default=0, verbose_name='设备状态')
    manufacturer = models.ForeignKey('Manufacturer', null=True, blank=True, verbose_name='制造商',
                                     on_delete=models.SET_NULL)
    manage_ip = models.GenericIPAddressField(null=True, blank=True, verbose_name='管理IP')
    tags = models.ManyToManyField('Tag', blank=True, verbose_name='标签')
    admin = models.ForeignKey(User, null=True, blank=True, verbose_name='资产管理员', related_name='admin',
                              on_delete=models.SET_NULL)
    idc = models.ForeignKey('IDC', null=True, blank=True, verbose_name='所在机房', on_delete=models.SET_NULL)
    contract = models.ForeignKey('Contract', null=True, blank=True, verbose_name='合同', on_delete=models.SET_NULL)
    purchase_day = models.DateField(null=True, blank=True, verbose_name="购买日期")
    expire_day = models.DateField(null=True, blank=True, verbose_name="过保日期")
    price = models.FloatField(null=True, blank=True, verbose_name="价格")
    approved_by = models.ForeignKey(User, null=True, blank=True, verbose_name='批准人', related_name='approved_by',
                                    on_delete=models.SET_NULL)
    memo = models.TextField(null=True, blank=True, verbose_name='备注')
    c_time = models.DateTimeField(auto_now_add=True, verbose_name='批准日期')
    m_time = models.DateTimeField(auto_now=True, verbose_name='更新日期')

    def __str__(self):
        return '<%s>  %s' % (self.get_asset_type_display(), self.name)

    class Meta:
        verbose_name = '资产总表'
        verbose_name_plural = "资产总表"
        ordering = ['-c_time']


class Server(models.Model):
    """服务器设备"""

    """
    每台服务器都唯一关联着一个资产对象，因此使用OneToOneField构建了一个一对一字段，这非常重要!
    服务器又可分为几种子类型，这里定义了三种；
    服务器添加的方式可以分为手动和自动；
    有些服务器是虚拟机或者docker生成的，没有物理实体，存在于宿主机中，因此需要增加一个hosted_on字段；
    这里认为，宿主机如果被删除，虚拟机也就不存在了；
    服务器有型号信息，如果硬件信息中不包含，那么指的就是主板型号；
    Raid类型在采用了Raid的时候才有，否则为空
    操作系统相关信息包含类型、发行版本和具体版本。
    """

    sub_asset_type_choice = (
        (0, 'PC服务器'),
        (1, '刀片机'),
        (2, '小型机'),
    )

    created_by_choice = (
        ('auto', '自动添加'),
        ('manual', '手工录入'),
    )

    asset = models.OneToOneField('Asset', on_delete=models.CASCADE)  # 非常关键的一对一关联！asset被删除的时候一并删除server
    sub_asset_type = models.SmallIntegerField(choices=sub_asset_type_choice, default=0, verbose_name="服务器类型")
    created_by = models.CharField(choices=created_by_choice, max_length=32, default='auto', verbose_name="添加方式")
    hosted_on = models.ForeignKey('self', related_name='hosted_on_server',
                                  blank=True, null=True, verbose_name="宿主机", on_delete=models.CASCADE)  # 虚拟机专用字段
    model = models.CharField(max_length=128, null=True, blank=True, verbose_name='服务器型号')
    raid_type = models.CharField(max_length=512, blank=True, null=True, verbose_name='Raid类型')
    os_type = models.CharField('操作系统类型', max_length=64, blank=True, null=True)
    os_distribution = models.CharField('发行商', max_length=64, blank=True, null=True)
    os_release = models.CharField('操作系统版本', max_length=64, blank=True, null=True)

    def __str__(self):
        return '%s--%s--%s <sn:%s>' % (self.asset.name, self.get_sub_asset_type_display(), self.model, self.asset.sn)

    class Meta:
        verbose_name = '服务器'
        verbose_name_plural = "服务器"


"""
每台安全、网络、存储设备都通过一对一的方式唯一关联这一个资产对象。
通过sub_asset_type又细分设备的子类型
对于软件，它没有物理形体，因此无须关联一个资产对象；
软件只管理那些大型的收费软件，关注点是授权数量和软件版本。对于那些开源的或者免费的软件，显然不算公司的资产。
"""


class SecurityDevice(models.Model):
    """安全设备"""

    sub_asset_type_choice = (
        (0, '防火墙'),
        (1, '入侵检测设备'),
        (2, '互联网网关'),
        (4, '运维审计系统'),
    )

    asset = models.OneToOneField('Asset', on_delete=models.CASCADE)
    sub_asset_type = models.SmallIntegerField(choices=sub_asset_type_choice, default=0, verbose_name="安全设备类型")
    model = models.CharField(max_length=128, default='未知型号', verbose_name='安全设备型号')

    def __str__(self):
        return self.asset.name + "--" + self.get_sub_asset_type_display() + str(self.model) + " id:%s" % self.id

    class Meta:
        verbose_name = '安全设备'
        verbose_name_plural = "安全设备"


class StorageDevice(models.Model):
    """存储设备"""

    sub_asset_type_choice = (
        (0, '磁盘阵列'),
        (1, '网络存储器'),
        (2, '磁带库'),
        (4, '磁带机'),
    )

    asset = models.OneToOneField('Asset', on_delete=models.CASCADE)
    sub_asset_type = models.SmallIntegerField(choices=sub_asset_type_choice, default=0, verbose_name="存储设备类型")
    model = models.CharField(max_length=128, default='未知型号', verbose_name='存储设备型号')

    def __str__(self):
        return self.asset.name + "--" + self.get_sub_asset_type_display() + str(self.model) + " id:%s" % self.id

    class Meta:
        verbose_name = '存储设备'
        verbose_name_plural = "存储设备"


class NetworkDevice(models.Model):
    """网络设备"""

    sub_asset_type_choice = (
        (0, '路由器'),
        (1, '交换机'),
        (2, '负载均衡'),
        (4, 'VPN设备'),
    )

    asset = models.OneToOneField('Asset', on_delete=models.CASCADE)
    sub_asset_type = models.SmallIntegerField(choices=sub_asset_type_choice, default=0, verbose_name="网络设备类型")

    vlan_ip = models.GenericIPAddressField(blank=True, null=True, verbose_name="VLanIP")
    intranet_ip = models.GenericIPAddressField(blank=True, null=True, verbose_name="内网IP")

    model = models.CharField(max_length=128, default='未知型号',  verbose_name="网络设备型号")
    firmware = models.CharField(max_length=128, blank=True, null=True, verbose_name="设备固件版本")
    port_num = models.SmallIntegerField(null=True, blank=True, verbose_name="端口个数")
    device_detail = models.TextField(null=True, blank=True, verbose_name="详细配置")

    def __str__(self):
        return '%s--%s--%s <sn:%s>' % (self.asset.name, self.get_sub_asset_type_display(), self.model, self.asset.sn)

    class Meta:
        verbose_name = '网络设备'
        verbose_name_plural = "网络设备"


class Software(models.Model):
    """
    只保存付费购买的软件
    """
    sub_asset_type_choice = (
        (0, '操作系统'),
        (1, '办公\开发软件'),
        (2, '业务软件'),
    )

    sub_asset_type = models.SmallIntegerField(choices=sub_asset_type_choice, default=0, verbose_name="软件类型")
    license_num = models.IntegerField(default=1, verbose_name="授权数量")
    version = models.CharField(max_length=64, unique=True, help_text='例如: RedHat release 7 (Final)',
                               verbose_name='软件/系统版本')
    c_time = models.DateTimeField(auto_now_add=True, verbose_name='批准日期')
    m_time = models.DateTimeField(auto_now=True, verbose_name='更新日期')

    def __str__(self):
        return '%s--%s' % (self.get_sub_asset_type_display(), self.version)

    class Meta:
        verbose_name = '软件/系统'
        verbose_name_plural = "软件/系统"
        ordering = ['-id']


class CPU(models.Model):
    """CPU组件"""

    asset = models.OneToOneField('Asset', on_delete=models.CASCADE)  # 设备上的cpu肯定都是一样的，所以不需要建立多个cpu数据，一条就可以，因此使用一对一。
    cpu_model = models.CharField('CPU型号', max_length=128, blank=True, null=True)
    cpu_count = models.PositiveSmallIntegerField('物理CPU个数', default=1)
    cpu_core_count = models.PositiveSmallIntegerField('CPU核数', default=1)

    def __str__(self):
        return self.asset.name + ":   " + self.cpu_model

    class Meta:
        verbose_name = 'CPU'
        verbose_name_plural = "CPU"


class RAM(models.Model):
    """内存组件"""

    asset = models.ForeignKey('Asset', on_delete=models.CASCADE)
    sn = models.CharField('SN号', max_length=128, blank=True, null=True)
    model = models.CharField('内存型号', max_length=128, blank=True, null=True)
    manufacturer = models.CharField('内存制造商', max_length=128, blank=True, null=True)
    slot = models.CharField('插槽', max_length=64)
    capacity = models.IntegerField('内存大小(GB)', blank=True, null=True)

    def __str__(self):
        return '%s: %s: %s: %s' % (self.asset.name, self.model, self.slot, self.capacity)

    class Meta:
        verbose_name = '内存'
        verbose_name_plural = "内存"
        unique_together = ('asset', 'slot')  # 同一资产下的内存，根据插槽的不同，必须唯一


class Disk(models.Model):
    """硬盘设备"""

    disk_interface_type_choice = (
        ('SATA', 'SATA'),
        ('SAS', 'SAS'),
        ('SCSI', 'SCSI'),
        ('SSD', 'SSD'),
        ('unknown', 'unknown'),
    )


login/models.py
from django.db import models

# Create your models here.


class User(models.Model):
    SEX_CHOICES = (
        ('male', "男"),
        ('female', "女"),
    )
    STATUS_CHOICES = (
        (0, '启用'),
        (1, '禁用'),
    )
    username = models.CharField(max_length=64, unique=True, verbose_name='用户名')
    nickname = models.CharField(max_length=64, blank=True, null=True, verbose_name='昵称')
    password = models.CharField(max_length=256, verbose_name='密码')
    email = models.EmailField(unique=True, verbose_name='邮箱')
    sex = models.CharField(max_length=32, choices=SEX_CHOICES, default="男", verbose_name='性别')
    status = models.SmallIntegerField(default=0, choices=STATUS_CHOICES, verbose_name='账号状态')
    create_time = models.DateTimeField(auto_now_add=True, verbose_name='创建时间')

    def __str__(self):
        return self.username + ', ' + self.nickname

    class Meta:
        ordering = ["-create_time"]
        verbose_name = "用户"
        verbose_name_plural = "用户"


class LoginLog(models.Model):
    event_type_choice = (
        (0, '其他'),
        (1, '登陆'),
        (2, '退出'),
        (3, '登陆错误'),
        (4, '修改密码失败'),
        (5, '修改密码成功'),
    )
    user = models.ForeignKey('User', blank=True, null=True, on_delete=models.SET_NULL, verbose_name='用户名')
    event_type = models.SmallIntegerField('事件类型', choices=event_type_choice, default=1)
    detail = models.TextField('事件详情', default='登陆成功')
    address = models.GenericIPAddressField('IP地址', blank=True, null=True)
    useragent = models.CharField(max_length=512, blank=True, null=True, verbose_name='User_Agent')
    create_time = models.DateTimeField('事件时间', auto_now_add=True)

    def __str__(self):
        return self.user.username

    class Meta:
        ordering = ["-create_time"]
        verbose_name = '登陆日志'
        verbose_name_plural = '登陆日志'


assets/forms.py
from django import forms


class SoftwareForm(forms.Form):
    subassettype = forms.IntegerField(label="软件类型")
    licensenum = forms.IntegerField(label="授权数量")
    version = forms.CharField(label="软件/系统版本", min_length=1, max_length=64)
    

templates/assets/hardware.html
{% extends 'base.html' %}
{% load static %}


  {% block title %}
  <title>硬件资产列表</title>
  {% endblock title %}
		  
		  {% block leftnav %}
          <li class="nav-item">
            <a href="{% url 'assets:index' %}" class="nav-link">
              <i class="nav-icon fas fa-tachometer-alt"></i>
              <p>
                仪表盘
              </p>
            </a>
          </li>
		  
		  <li class="nav-item">
            <a href="{% url 'assets:hardware' %}" class="nav-link active">
              <i class="nav-icon fas fa-copy"></i>
              <p>
                硬件资产
              </p>
            </a>
          </li>
		  
		  <li class="nav-item">
            <a href="{% url 'assets:software' %}" class="nav-link">
              <i class="nav-icon far fa-credit-card"></i>
              <p>
                软件资产
              </p>
            </a>
          </li>
		  <li class="nav-item has-treeview">
            <a href="#" class="nav-link">
			  <i class="nav-icon fas fa-history"></i>
              <p>
                日志审计
                <i class="right fas fa-angle-left"></i>
              </p>
            </a>
            <ul class="nav nav-treeview">
              <li class="nav-item">
                <a href="{% url 'assets:audit_login' %}" class="nav-link">
                  <i class="fas fa-user-edit nav-icon"></i>
                  <p>用户日志</p>
                </a>
              </li>
              <li class="nav-item">
                <a href="{% url 'assets:operation' %}" class="nav-link">
                  <i class="fas fa-wrench nav-icon"></i>
                  <p>操作日志</p>
                </a>
              </li>
            </ul>
          </li>
		  {% endblock leftnav %}

    {% block navheader %}
    <section class="content-header">
      <div class="container-fluid">
        <div class="row mb-1">
          <div class="col-12">
            <ol class="breadcrumb">
              <li class="breadcrumb-item"><a href="{% url 'assets:index' %}">首页</a></li>
              <li class="breadcrumb-item active">硬件资产列表</li>
            </ol>
          </div>
        </div>
      </div><!-- /.container-fluid -->
    </section>
	{% endblock navheader %}


		  {% block content %}
          <div class="card">
            <div class="card-header">
              <h3 class="card-title">硬件资产列表<a href="javascript:void(0)" class="btn btn-sm btn-info ml-3">新增 + </a></h3>
				<div class="card-tools">
				  <button type="button" class="btn btn-tool" data-widget="collapse">
					<i class="fas fa-minus"></i>
				  </button>
				  <button type="button" class="btn btn-tool" data-widget="remove">
					<i class="fas fa-times"></i>
				  </button>
				</div>
            </div>
            <!-- /.card-header -->
            <div class="card-body">
              <table id="assets-lists" class="table table-bordered table-striped">
                <thead>
                <tr>
				  <th>资产类型</th>
				  <th>子类型</th>
				  <th>资产名称</th>
				  <th>SN序列号</th>
				  <th>业务线</th>
				  <th>状态</th>
				  <th>机房</th>
				  <th>添加日期</th>
				  <th>更新日期</th>
				  <th>标签</th>
				  <th>操作</th>
                </tr>
                </thead>
                <tbody>
				{% for asset in assets %}
                <tr id="asset-{{ asset.id }}">
                  {% if asset.asset_type == 'server' %}
                      <td class="text-bold" style="color:green;">{{ asset.get_asset_type_display }}</td>
                      <td>{{ asset.server.get_sub_asset_type_display }}</td>
                  {% elif asset.asset_type == "networkdevice" %}
                      <td class="text-bold" style="color:gray;">{{ asset.get_asset_type_display }}</td>
                      <td>{{ asset.networkdevice.get_sub_asset_type_display }}</td>
                  {% elif asset.asset_type == "storagedevice" %}
                      <td class="text-bold" style="color:blue;">{{ asset.get_asset_type_display }}</td>
                      <td>{{ asset.storagedevice.get_sub_asset_type_display }}</td>
                  {% elif asset.asset_type == "securitydevice" %}
                      <td class="text-bold" style="color:red;">{{ asset.get_asset_type_display }}</td>
                      <td>{{ asset.securitydevice.get_sub_asset_type_display }}</td>
                  {% endif %}
				  
				  {% if asset.asset_type == 'server' %}
				  <td><a href="{% url 'assets:detail' asset.id %}">{{ asset.name }}</a></td>
				  {% else %}
				  <td>{{ asset.name }}</td>
				  {% endif %}
				  
				  <td>{{ asset.sn }}</td>
				  <td>{{ asset.business_unit | default_if_none:"-" }}</td>
				  
				  {% if asset.status == 0 %}
				  <td><label class="label label-success">{{ asset.get_status_display }}</label></td>
				  {% elif asset.status == 1 %}
				  <td><label class="label label-warning">{{ asset.get_status_display }}</label></td>
				  {% elif asset.status == 2 %}
				  <td><label class="label label-default">{{ asset.get_status_display }}</label></td>
				  {% elif asset.status == 3 %}
				  <td><label class="label label-danger">{{ asset.get_status_display }}</label></td>
				  {% elif asset.status == 4 %}
				  <td><label class="label label-info">{{ asset.get_status_display }}</label></td>
				  {% endif %}
				  
				  <td>{{ asset.idc|default:"-" }}</td>
				  <td>{{ asset.c_time|date:"Y/m/d H:m:s" }}</td>
				  <td>{{ asset.m_time|date:"Y/m/d H:m:s" }}</td>
				  <td>
					  {% for tag in asset.tags.all %}
                        <label class="label label-primary">{{ tag.name }}</label>
                      {% empty %}
                          -
                      {% endfor %}
				  </td>
				  <td>
					<a href="#">修改</a> 
					<a href="javascript:void(0);" id="{{ asset.id }}" onclick="createmodal(this);" title="{{ asset.get_asset_type_display }},{{ asset.name }}">删除</a>
				  </td>
                </tr>
				{% empty %}
                <tr>没有数据！</tr>
				{% endfor %}
                </tbody>
                <tfoot>
                <tr>
				  <th>资产类型</th>
				  <th>子类型</th>
				  <th>资产名称</th>
				  <th>SN序列号</th>
				  <th>业务线</th>
				  <th>状态</th>
				  <th>机房</th>
				  <th>添加日期</th>
				  <th>更新日期</th>
				  <th>标签</th>
				  <th>操作</th>
                </tr>
                </tfoot>
              </table>
            </div>
            <!-- /.card-body -->
          </div>
          <!-- /.card -->
		  <!--删除确认窗口-->
		  <div id="modal-container">
		  </div>		  
		  {% endblock content %}

{% block js %}
<!-- 删除 -->
<script>
	createmodal = function (event) {
		var thisObj = $(event);	//js对象转jquery对象  
		var asset_id = thisObj.attr('id');
		var asset_name = thisObj.attr("title");

		// 生成弹出框，使用 \ 换行
		$("#modal-container").html('<div id="modal-delete-' + asset_id + '" class="iziModal"><div class="container-fluid"><div class="row">\
									<div class="col-12 p-3"><h5 class="text-center mt-3">确定要删除 <' + asset_name + '> 吗？</h5></div><div class="col-6 p-3">\
									<button type="button" class="btn btn-block btn-secondary btn-flat" data-iziModal-close>取消</button></div><div class="col-6 p-3">\
									<a href="javascript:void(0)"><button type="button" class="btn btn-block btn-success btn-flat" id="' + asset_id + '-yes" title="\
									' + asset_name + '" onclick="deletehardware(this);">确定</button></a></div></div></div></div>');
		
		// 初始化弹出框
		$("#modal-delete-" + asset_id).iziModal({
			iconClass: 'icon-announcement',
			width: 450,
			padding: 10,
			overlayClose: false,	// 是否允许点击模态窗口的外部来关闭模态窗口。
			closeOnEscape: false, 	// 是否允许通过点击ESC键来关闭模态窗口。
		});
				
		// 打开弹出框
		$('#modal-delete-' + asset_id).iziModal('open');
	}
	
		
	deletehardware = function(event) {
		toastr.options.closeButton = true;
		toastr.options.showMethod = 'slideDown';
		toastr.options.hideMethod = 'fadeOut';
		toastr.options.closeMethod = 'fadeOut';
		toastr.options.timeOut = 4000;	
		toastr.options.extendedTimeOut = 0;	
		
		var thisObj = $(event);	//js对象转jquery对象
		var asset_id = thisObj.attr('id').split("-")[0];
		var asset_name = thisObj.attr("title");
		csrfmiddlewaretoken = '{{ request.COOKIES.csrftoken }}';
		$.ajax({
			url: "{% url 'assets:hardware_delete' %}",
			async: true,
			type: 'POST',
			dataType: 'json',
			data: {
				'csrfmiddlewaretoken': csrfmiddlewaretoken,
				'id': asset_id,
			},
			timeout: 10000,
			cache: true,
			beforeSend: LoadFunction, //加载执行方法
			error: errFunction,  //错误执行方法
			success: succFunction, //成功执行方法
		});
		
		function LoadFunction() {
			//$("#aboutcontent").html('删除中...');
			//alert('删除中');
		};
		
		function errFunction() {
			// 关闭弹出框
			$('#modal-delete-' + asset_id).iziModal('close');
			// 消息框
			toastr.error('删除错误 <' + asset_name + '>');
		};
		
		function succFunction(res) {
			if (res.code != 200) {
				// 关闭弹出框
				$('#modal-delete-' + asset_id).iziModal('close');
				// 消息框
				toastr.error('删除错误 <' + asset_name + '>');
			} else {
				// 先销毁 datatable , 动态删除数据后，然后再重建
				var dttable = $('#assets-lists').DataTable();
				dttable.destroy();
				
				$("#asset-" + asset_id).remove();
				
				$("#assets-lists").DataTable({
					language: {
						"sProcessing": "处理中...",
						"sLengthMenu": "显示 _MENU_ 项结果",
						"sZeroRecords": "没有匹配结果",
						"sInfo": "显示第 _START_ 至 _END_ 项结果，共 _TOTAL_ 项",
						"sInfoEmpty": "显示第 0 至 0 项结果，共 0 项",
						"sInfoFiltered": "(由 _MAX_ 项结果过滤)",
						"sInfoPostFix": "",
						"sSearch": "搜索:",
						"sUrl": "",
						"sEmptyTable": "表中数据为空",
						"sLoadingRecords": "载入中...",
						"sInfoThousands": ",",
						"oPaginate": {
							"sFirst": "首页",
							"sPrevious": "上页",
							"sNext": "下页",
							"sLast": "末页"
						},
						"oAria": {
							"sSortAscending": ": 以升序排列此列",
							"sSortDescending": ": 以降序排列此列"
						}
					},
					destroy: true,	// 允许重建
					bProcessing:true,  // 表格数据过多处理时显示: sProcessing
					lengthMenu: [[10, 25, 50, 100, -1], [10, 25, 50, 100, "全部"]],
					order: [],
					 scrollY: 480,	// 滚动条
					 scrollCollapse: true,
					 jQueryUI: true,
					 stateSave: true,	// 保存最后一次分页信息、排序信息，当页面刷新，或者重新进入这个页面，恢复上次的状态。
					 stateDuration: 86400,	// 本地储存(0~更大)还是session储存(-1) 
				});
				
				// 关闭弹出框
				$('#modal-delete-' + asset_id).iziModal('close');
				
				// 消息框
				toastr.success('成功删除 <' + asset_name + '>');
			}
		};
	}
	
</script>
{% endblock js %}